### ISSUE TITLE
Cant turn off light using Arlec-Grid-Connect-Smart_LED-Globe-CWWW

### ISSUE THREAD

**Issue by muzzak123** [jonathanadams/esphome-configs#90]
Hi, Thx for you work with the Arlec-Grid-Connect-Smart_LED-Globe-CWWW config. I've flashed my light with it and can now do transitions, but when I try to turn it off using the Homes Assistant entity the log shows
[11:53:48][D][light:273]:   State: OFF
[11:53:48][D][light:303]:   Transition Length: 1.0s
but nothing happens. It just stays on.

**Comment by jonathanadams** [comment]
Are you using exactly the same config as what is in the repo/website. If not can you post your config and I will see if i can help?

**Comment by muzzak123** [comment]
My config is:

```
esphome:

  includes:
    - esphome_arlec_light_component.h

  name: arlec_smart_globe
  platform: ESP8266
  board: esp01_1m
  esp8266_restore_from_flash: true

wifi:
  ssid: MYSSID
  password: MYPASSWORD
  reboot_timeout: 0s
  manual_ip:
    static_ip: 192.168.0.30
    gateway: 192.168.0.1
    subnet: 255.255.255.0

  ap:
    ssid: "Globe Fallback Hotspot"
    password: "password"

captive_portal:

logger:

api:
  reboot_timeout: 0s
  password: "MYPWD"

ota:
  password: "MYPWD"
  
output:
  - platform: esp8266_pwm
    id: dimmer
    pin: GPIO5
  - platform: esp8266_pwm
    id: color_temp
    pin: GPIO13

light:
  - platform: custom
    lambda: |-
      auto light_out = new ArlecCustomLight(id(dimmer), id(color_temp));
      App.register_component(light_out);
      return {light_out};
    lights:
      - name: "Study Overhead"
        restore_mode: RESTORE_DEFAULT_ON
```
